name: "ESP8266-RTOS-SDK (IDF Style) Build"
description: "This action build your firmware directly in github using Espressif Native SDK and Toolkit."
branding:
  color: blue
  icon: check
inputs:
  makearg:
    description: "Arguments to pass for make"
    required: false
    default: "defconfig all size-components"
runs:
  using: "docker"
  image: "docker://nsfilho/esp8266-rtos-sdk:3.4"
  args:
    - ${{ inputs.makearg }}
