# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [master]
    paths:
      - Dockerfile
      - entrypoint.sh

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building docker image
        run: |
          docker build --rm=true --force-rm=true -t airmeter-io/esp8266-rtos-sdk:3.4 ./
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_STORE_USERNAME }}
          password: ${{ secrets.DOCKER_STORE_PASSWORD }}
          repository: airmeter-io/esp8266-rtos-sdk
          tags: 3.4
          tag_with_ref: false
